# Generated by Django 4.2.16 on 2024-09-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('completed', 'completed'), ('upcoming', 'upcoming')], max_length=25, null=True),
        ),
    ]
