# Generated by Django 4.2.16 on 2024-09-20 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_details',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_details', to='app1.register'),
        ),
    ]
