# Generated by Django 4.2.16 on 2024-09-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_work_details_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='access',
            field=models.CharField(choices=[('superuser', 'superuser'), ('admin', 'admin'), ('user', 'user')], default='user', max_length=20, null=True),
        ),
    ]
