# Generated by Django 4.2.16 on 2024-09-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_leave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='leave',
            new_name='leave1',
        ),
    ]
